name: agendario
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Base de Datos Local
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.1.0

  # Utilidades & UI
  provider: ^6.1.1
  flutter_markdown: ^0.6.18+2
  uuid: ^4.2.2
  intl: ^0.19.0

  # IA & Cloud (Se pueden configurar luego)
  google_generative_ai: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Generadores de cÃ³digo
  isar_generator: ^3.1.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
